---
apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: restcreatecustomer
  spec:
    tags:
    - from:
        kind: ImageStreamImage
        name: restcreatecustomer@sha256:8a32694f406d72472409df24f5543430ddb2e12aa89ee05837f9666052f71d47
        namespace: fuse
      name: latest
